### PR TITLE
refactor: make app standalone and remove modules

### PR DESCRIPTION
**Pull request by sheikalthaf**
- Make components standalone
- Remove Modules
- Refactor routes
- Made app standalone and use provides
- Add SSR support

### CODE REVIEW

**Comment by geromegrignon** [comment]
Hello @sheikalthaf this pull request is covering too many topics to be reviewed as a single one. I also encourage you to communicate with the team with issues before working on such a big work. Because for example, there is no plan to support SSR so far.

**Comment by geromegrignon** [comment]
Standalone might be good as a lone topic, you also need to rebase your branch as it includes an unwanted commit here.

**Comment by sheikalthaf** [comment]
> Hello @sheikalthaf this pull request is covering too many topics to be reviewed as a single one. I also encourage you to communicate with the team with issues before working on such a big work. Because for example, there is no plan to support SSR so far.

Thanks for your feedback. I just wanted to convert the app to standalone, but I don't know that SSR is removed. I'll remove the SSR from my PR. Also i have added multiple commits for easy review.

**Comment by geromegrignon** [comment]
Thanks for the consideration of review with separate commits but it won't help in fact: by focusing on separate reviews, I would not get the global vision of the project and might not know if all Components moved to Standalone.

Thanks for the contribution!

**Comment by sheikalthaf** [comment]
@geromegrignon ok i got your point, maybe i can create multiple small PRs for easy review.

**Comment by geromegrignon** [comment]
@sheikalthaf with only the standalone focus, this PR is perfect!

**Comment by sheikalthaf** [comment]
Closing this PR, and creating multiple PRs for the same

**Pull request closed without merging**
