### PR TITLE
PR: Update best practices

### PR DESCRIPTION
**Pull request by eduardoRoth**
In this PR I made the following changes:

- I removed the topic about using AOT compiler in Angular apps, as since v9 it's the default compiler.
- I fixed a typo in the topic `never mutate objects and embrace immutability`, a duplicated `are`
- Included a caution warning about using template bound functions and the performance hit that they take in Angular apps when using the default change strategy
- Added a topic about the use of enums for multiple already known possible values variables
- Added a topic about using component state (inside NgRx).

Following PRs will be one per modification.

### CODE REVIEW

**Comment by geromegrignon** [comment]
Hey @eduardoRoth, I encourage you to make more specific and distinct PRs: it will help the maintainers review them.

**Comment by eduardoRoth** [comment]
> Hey @eduardoRoth, I encourage you to make more specific and distinct PRs: it will help the maintainers review them.

Sure @geromegrignon , I'll modify the PR to include everything that I modified. Thanks 😄

**Comment by geromegrignon** [comment]
I mean you should make separate PRs: some content might be biased and would require discussion (or might be refused).
It would delay the whole PR.

here is a recommendation from one of the maintainers:
> I would try to keep PR's as small as possible. The sooner you submit something, the sooner we can provide feedback. :)

**Comment by eduardoRoth** [comment]
> I mean you should make separate PRs: some content might be biased and would require discussion (or might be refused). It would delay the whole PR.
> 
> here is a recommendation from one of the maintainers:
> 
> > I would try to keep PR's as small as possible. The sooner you submit something, the sooner we can provide feedback. :)

Ok, I'll make the change 😄

**Pull request closed without merging**
